name: AI Code Analysis Report

on:
  # Use pull_request_target to allow comments on forked PRs
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  call-ai-analysis:
    uses: prince-deriv/shared-actions/.github/workflows/ai-code-analysis.yml@3d2ece1d169b526d9ab8bbd797bbe7a3bdd9a72f
    secrets: inherit
