name: AI Analysis History Tracker

on:
  # Allow calling from other repositories
  workflow_call:
  
  # Use pull_request_target to allow file commits even from forks
  pull_request_target:
    types: [closed]
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write

jobs:
  check-if-dashboard-pr:
    # Run this job to check if we should skip due to dashboard PR loop prevention
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.check.outputs.should-skip }}
      skip-reason: ${{ steps.check.outputs.skip-reason }}
    steps:
      - name: Check if this is a dashboard update PR
        id: check
        run: |
          echo "🔍 Checking if this PR should trigger dashboard update..."
          echo ""
          echo "PR Details:"
          echo "  Title: ${{ github.event.pull_request.title }}"
          echo "  Branch: ${{ github.event.pull_request.head.ref }}"
          echo "  Author: ${{ github.event.pull_request.user.login }}"
          echo ""
          
          SHOULD_SKIP="false"
          SKIP_REASON=""
          
          if [[ "${{ github.event.pull_request.title }}" == *"📊 Dashboard Update"* ]]; then
            SHOULD_SKIP="true"
            SKIP_REASON="PR title contains '📊 Dashboard Update'"
          elif [[ "${{ github.event.pull_request.title }}" == *"📊 Update AI Code Analysis Dashboard"* ]]; then
            SHOULD_SKIP="true"
            SKIP_REASON="PR title contains '📊 Update AI Code Analysis Dashboard'"
          elif [[ "${{ github.event.pull_request.head.ref }}" == dashboard-update-* ]]; then
            SHOULD_SKIP="true"
            SKIP_REASON="PR branch starts with 'dashboard-update-'"
          elif [[ "${{ github.event.pull_request.user.login }}" == "github-actions[bot]" ]]; then
            SHOULD_SKIP="true"
            SKIP_REASON="PR author is github-actions[bot]"
          fi
          
          if [[ "$SHOULD_SKIP" == "true" ]]; then
            echo "🔄 ✅ SKIPPING: $SKIP_REASON"
            echo "💡 This prevents infinite loops of dashboard updates triggering more dashboard updates"
          else
            echo "✅ PROCEEDING: This PR should trigger dashboard update"
          fi
          
          echo "should-skip=$SHOULD_SKIP" >> $GITHUB_OUTPUT
          echo "skip-reason=$SKIP_REASON" >> $GITHUB_OUTPUT

  update-ai-history:
    # Only run if PR was actually merged AND it's not a dashboard update PR (to prevent loops)
    needs: check-if-dashboard-pr
    if: needs.check-if-dashboard-pr.outputs.should-skip == 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # For pull_request_target, ensure we have the main branch for dashboard updates
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.4
        with:
          node-version: '18'

      - name: Extract AI analysis from PR
        id: extract-analysis
        run: |
          node -e "
          const https = require('https');
          const fs = require('fs');
          
          const TOKEN = '${{ secrets.GITHUB_TOKEN }}';
          const REPO = '${{ github.repository }}';
          const PR_NUMBER = ${{ github.event.number }};
          
          function makeRequest(path) {
            return new Promise((resolve, reject) => {
              const options = {
                hostname: 'api.github.com',
                path: path,
                headers: {
                  'Authorization': 'token ' + TOKEN,
                  'User-Agent': 'Merged-PR-Tracker',
                  'Accept': 'application/vnd.github.v3+json'
                }
              };
              
              const req = https.request(options, (res) => {
                let data = '';
                res.on('data', chunk => data += chunk);
                res.on('end', () => resolve(JSON.parse(data)));
              });
              req.on('error', reject);
              req.end();
            });
          }
          
          function extractAIAnalysis(comment) {
            if (!comment.body.includes('🤖 AI Code Analysis')) return null;
            
            const jsonMatch = comment.body.match(/\`\`\`json\\n([\\s\\S]*?)\\n\`\`\`/);
            if (!jsonMatch) return null;
            
            try {
              const data = JSON.parse(jsonMatch[1]);
              if (data.summary && data.files && data.timestamp) return data;
            } catch (e) {}
            
            return null;
          }
          
          async function main() {
            console.log('Extracting AI analysis for merged PR #' + PR_NUMBER);
            
            // Get comments for this PR
            const comments = await makeRequest('/repos/' + REPO + '/issues/' + PR_NUMBER + '/comments');
            
            // Find AI analysis comments (get the latest one)
            const aiComments = comments
              .filter(c => c.body.includes('🤖 AI Code Analysis'))
              .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
            
            if (aiComments.length === 0) {
              console.log('ERROR: No AI analysis found for PR #' + PR_NUMBER);
              
              // Create a basic entry even without analysis
              const basicEntry = {
                timestamp: new Date().toISOString(),
                repository: REPO,
                pullRequest: PR_NUMBER,
                branch: '${{ github.event.pull_request.head.ref }}',
                author: '${{ github.event.pull_request.user.login }}',
                prTitle: '${{ github.event.pull_request.title }}',
                prUrl: '${{ github.event.pull_request.html_url }}',
                mergedAt: '${{ github.event.pull_request.merged_at }}',
                summary: {
                  totalCharacters: 0,
                  aiCharacters: 0,
                  percentage: 0
                },
                files: [],
                hasAnalysis: false
              };
              
              fs.writeFileSync('merged_pr_data.json', JSON.stringify(basicEntry, null, 2));
              return;
            }
            
            console.log('SUCCESS: Found AI analysis for PR #' + PR_NUMBER);
            
            const analysis = extractAIAnalysis(aiComments[0]);
            if (!analysis) {
              console.log('ERROR: Could not parse AI analysis data');
              return;
            }
            
            // Enhance analysis with PR metadata
            analysis.prTitle = '${{ github.event.pull_request.title }}';
            analysis.prUrl = '${{ github.event.pull_request.html_url }}';
            analysis.mergedAt = '${{ github.event.pull_request.merged_at }}';
            analysis.hasAnalysis = true;
            
            console.log('PR #' + PR_NUMBER + ': ' + analysis.summary.percentage + '% AI (' + analysis.files.length + ' files)');
            
            fs.writeFileSync('merged_pr_data.json', JSON.stringify(analysis, null, 2));
          }
          
          main().catch(console.error);
          "

      - name: Update historical data
        run: |
          # Create data directory if it doesn't exist
          mkdir -p .github/data
          
          # Initialize history file if it doesn't exist
          if [ ! -f ".github/data/ai-analysis-history.json" ]; then
            echo '{"lastUpdated": "", "totalMergedPRs": 0, "analyses": []}' > .github/data/ai-analysis-history.json
          fi
          
          # Add new entry to history
          node -e "
          const fs = require('fs');
          
          // Read existing history
          const history = JSON.parse(fs.readFileSync('.github/data/ai-analysis-history.json', 'utf8'));
          
          // Read new PR data
          if (fs.existsSync('merged_pr_data.json')) {
            const newEntry = JSON.parse(fs.readFileSync('merged_pr_data.json', 'utf8'));
            
            // Check if this PR is already in history (avoid duplicates)
            const existingIndex = history.analyses.findIndex(
              a => a.repository === newEntry.repository && a.pullRequest === newEntry.pullRequest
            );
            
            if (existingIndex >= 0) {
              // Update existing entry
              history.analyses[existingIndex] = newEntry;
              console.log('📝 Updated existing entry for PR #' + newEntry.pullRequest);
            } else {
              // Add new entry
              history.analyses.push(newEntry);
              console.log('➕ Added new entry for PR #' + newEntry.pullRequest);
            }
            
            // Sort by merged date (newest first)
            history.analyses.sort((a, b) => new Date(b.mergedAt || b.timestamp) - new Date(a.mergedAt || a.timestamp));
            
            // Update metadata
            history.lastUpdated = new Date().toISOString();
            history.totalMergedPRs = history.analyses.length;
            
            // Save updated history
            fs.writeFileSync('.github/data/ai-analysis-history.json', JSON.stringify(history, null, 2));
            
            console.log('History updated: ' + history.totalMergedPRs + ' total merged PRs tracked');
          }
          "

      - name: Generate updated dashboard
        run: |
          node .github/scripts/generate-dashboard.js

      - name: Create/Update Dashboard PR  
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Define branch name first (before any potential exits)
          BRANCH_NAME="dashboard-update-$(date +%Y%m%d)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "🔧 Set BRANCH_NAME=$BRANCH_NAME"
          
          # Add all changes
          git add .github/data/ai-analysis-history.json AI-DASHBOARD.md
          
          # Only proceed if there are changes
          if git diff --staged --quiet; then
            echo "ℹ️  No changes to commit"
            exit 0
          fi
          
          # Check if branch already exists locally
          if git rev-parse --verify "$BRANCH_NAME" >/dev/null 2>&1; then
            echo "📝 Switching to existing branch: $BRANCH_NAME"
            git checkout "$BRANCH_NAME"
            # Get latest changes from master
            git merge origin/master --no-edit
          else
            echo "🌿 Creating new branch: $BRANCH_NAME"
            git checkout -b "$BRANCH_NAME"
          fi
          
          # Re-add changes (in case of merge conflicts)
          git add .github/data/ai-analysis-history.json AI-DASHBOARD.md
          
          # Commit changes
          git commit -m "📊 Track merged PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}
          
          - Merged: ${{ github.event.pull_request.merged_at }}
          - Author: ${{ github.event.pull_request.user.login }}
          - Updated dashboard with historical data"
          
          # Push to remote (force to handle multiple updates to same branch)
          git push origin "$BRANCH_NAME" --force
          
          echo "✅ Changes pushed to branch: $BRANCH_NAME"
          echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Create or Update Pull Request
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const branchName = process.env.BRANCH_NAME;
            const prNumber = process.env.PR_NUMBER;
            const prTitle = process.env.PR_TITLE;
            const prAuthor = process.env.PR_AUTHOR;
            const { owner, repo } = context.repo;
            
            console.log('Environment check:');
            console.log('  BRANCH_NAME:', branchName);
            console.log('  PR_NUMBER:', prNumber);
            console.log('  PR_TITLE:', prTitle);
            console.log('  PR_AUTHOR:', prAuthor);
            console.log('  owner:', owner);
            console.log('  repo:', repo);
            
            if (!branchName || branchName.trim() === '') {
              throw new Error('BRANCH_NAME environment variable is not set or empty! Cannot create PR without head branch.');
            }
            
            // Check if PR already exists for this branch
            try {
              const { data: existingPRs } = await github.rest.pulls.list({
                owner,
                repo,
                head: `${owner}:${branchName}`,
                state: 'open'
              });
              
              const prBody = [
                '## 📊 AI Dashboard Update - Merged PRs Tracking',
                '',
                '🤖 This PR automatically tracks merged PRs and updates the AI Code Analysis Dashboard.',
                '',
                '### 🎯 Latest Merged PR:',
                '- **PR #' + prNumber + '**: ' + prTitle,
                '- **Author**: @' + prAuthor,
                '- **Merged**: ' + new Date().toISOString(),
                '',
                '### 📈 What\'s Updated:',
                '- `.github/data/ai-analysis-history.json` - Historical tracking data',
                '- `AI-DASHBOARD.md` - Updated dashboard with latest statistics',
                '',
                '### 🔄 Auto-Update Details:',
                '- **Trigger**: PR merge event',
                '- **Branch**: Daily consolidation (' + branchName + ')',
                '- **Multiple merges**: Updates accumulate in this single PR',
                '',
                '### 🎯 Next Steps:',
                '- Review the updated dashboard and historical data',
                '- Merge when ready to publish the latest AI analysis statistics',
                '',
                '---',
                '*🤖 This PR consolidates multiple merged PR updates into a single daily update. New merges will update this same PR until it\'s merged.*'
              ].join('\n');

              if (existingPRs.length > 0) {
                // Update existing PR
                const pr = existingPRs[0];
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: pr.number,
                  body: prBody
                });
                
                console.log('Updated existing dashboard PR #' + pr.number + ': ' + pr.html_url);
                console.log('Added data for merged PR #' + prNumber);
                
              } else {
                // Create new PR
                const { data: newPR } = await github.rest.pulls.create({
                  owner,
                  repo,
                  title: '📊 Dashboard Update - ' + new Date().toISOString().split('T')[0],
                  head: branchName,
                  base: 'master',
                  body: prBody,
                  draft: false
                });
                
                console.log('Created new dashboard PR #' + newPR.number + ': ' + newPR.html_url);
                console.log('Tracking merged PR #' + prNumber);
              }
              
            } catch (error) {
              console.error('Error managing dashboard PR:', error);
              throw error;
            }

      - name: Auto-merge Dashboard PR
        if: ${{ secrets.SHIFTAI_TOKEN != '' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.SHIFTAI_TOKEN }}
          script: |
            const branchName = process.env.BRANCH_NAME;
            const { owner, repo } = context.repo;
            
            console.log('SHIFTAI_TOKEN detected - attempting auto-merge...');
            console.log('Auto-merge environment check:');
            console.log('  BRANCH_NAME:', branchName);
            
            if (!branchName || branchName.trim() === '') {
              console.log('ERROR: BRANCH_NAME not set - cannot auto-merge');
              return;
            }
            
            try {
              // Find the dashboard PR
              const { data: existingPRs } = await github.rest.pulls.list({
                owner,
                repo,
                head: `${owner}:${branchName}`,
                state: 'open'
              });
              
              if (existingPRs.length > 0) {
                const pr = existingPRs[0];
                
                // Wait a moment for any checks to start
                await new Promise(resolve => setTimeout(resolve, 5000));
                
                // Auto-merge the PR
                await github.rest.pulls.merge({
                  owner,
                  repo,
                  pull_number: pr.number,
                  merge_method: 'squash',
                  commit_title: '📊 Auto-merged: AI Dashboard Update',
                  commit_message: 'Automatically merged dashboard update PR via SHIFTAI_TOKEN\n\n🤖 This PR was auto-merged using administrative privileges to maintain dashboard currency.'
                });
                
                console.log('SUCCESS: Auto-merged dashboard PR #' + pr.number);
                console.log('Dashboard is now live with latest data!');
                
              } else {
                console.log('WARNING: No open dashboard PR found to auto-merge');
              }
              
            } catch (error) {
              console.error('ERROR: Auto-merge failed:', error.message);
              console.log('PR will remain open for manual review and merge');
              // Don't throw - let workflow continue
            }

      - name: Output summary
        run: |
          echo "📊 Merged PR Tracking Complete!"
          echo ""
          echo "✅ Tracked PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}"
          echo "👤 Author: ${{ github.event.pull_request.user.login }}"
          echo "🕐 Merged: ${{ github.event.pull_request.merged_at }}"
          echo ""
          echo "🔄 Update process:"
          echo "   • ✅ Added to historical tracking data"
          echo "   • ✅ Generated updated dashboard"
          echo "   • Created/updated dashboard PR"
          if [ -n "${{ secrets.SHIFTAI_TOKEN }}" ]; then
            echo "   • 🤖 Auto-merge attempted (SHIFTAI_TOKEN detected)"
          else
            echo "   • ⏳ Waiting for PR review and merge"
          fi
          echo ""
          echo "🔗 Once dashboard PR is merged, view:"
          echo "   • Dashboard: https://github.com/${{ github.repository }}/blob/main/AI-DASHBOARD.md"
          echo "   • Historical data: https://github.com/${{ github.repository }}/blob/main/.github/data/ai-analysis-history.json"
          echo ""
          echo "🎯 Multiple merges today will update the same PR until it's merged!" 